config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
 
  devise_for :users
  root 'welcome#index'
      devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
    end
   
   get 'my_portfolio', to: 'users#my_portfolio'
   get 'search_stock', to: 'stocks#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
   has_many :user_stocks
   has_many :users, through: :user_stocks


 
    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: 
                                    Rails.application.credentials.iex_client[:iex_api_key],
                                    secret_token: 'sk_7d4983a3f6a54fd08d1dff51b82be876',
                                    endpoint: 'https://cloud.iexapis.com/v1')
        begin
          respnose = new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol)) 
          {success: true, data: response, message: "Successfully Fetched!!!"}
        rescue => e
          {success: false, data: nil, message: e}

        end
    end

    

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController


  	def search
        if	params[:stock].present?
        	@stock = Stock.new_lookup(params[:stock])
    
				if 	@stock[:success]
					flash[:alert] = "Success"
					redirect_to my_portfolio_path	
				else
					flash[:alert] = @stock[:message]
					redirect_to my_portfolio_path
				end
							
      	else
            flash[:alert] = "Please enter a symbol to search"
            redirect_to my_portfolio_path
        end
  	end


end
  

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
	<br>
        <div class='alert alert-success alert-dismissible'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
   <br>
	<div class='alert alert-danger alert-dismissible'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        
        <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
            <% if current_user %>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                    <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
                       
                    </ul>
                    <ul class='navbar-nav ml auto'>
                        <li class='nav-item'>
                            <%= link_to("Logout", destroy_user_session_path,
                            class: "btn btn-xs btn-danger logout-button", method: :delete)%>
                        </li>
                    </ul>
                        
                        <ul form class="form-inline my-0 my-lg-0">
                       
                            <li>
                                <input class="form-control me-4" type="search" placeholder="Search" aria-label="Search">
                            </li>
                        </ul>
                            <li>
                                <button class="btn btn-outline-success" type="submit">Search</button>
                            </li>
                    </form>
                </div>
            <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_result.html.erb
  <% if @stock %>
  <div class="card card-header results-block">
  <strong>Symbol: </strong> <%= @stock.ticker %>
  <strong>Name: </strong> <%= @stock.name %>
  <strong>Price: </strong> <%= @stock.last_price %>
  </div>
  <% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javescript(render 'users/result.html') %>'

app/views/users/my_portfolio.html.erb
<br>
<h1>My Portfolio</h1>
<br>

<div class='search-area'>
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote:true, method: :get do%>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock] , placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg"%>
            </div>

            
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
    
<div id="results">

</div>
 

app/views/welcome/index.html.erb
<br>
<h1>Welcome to the finance tracker application</h1>
<br><br>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>